# Generated by Django 3.2.5 on 2021-07-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_product_full_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='full_description',
            field=models.CharField(default='Введите описание', max_length=1000),
        ),
    ]
